---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "54f4418e-5d78-47c4-a352-70b3f3cfc6ff",
        "monitors": [
           "10.10.40.52:6789",
           "10.10.40.53:6789",
           "10.10.40.54:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
