apiVersion: v1
kind: ConfigMap
metadata:
  name: openstack-exporter-auth
data:
  clouds.yaml: |-
    clouds:
      default:
        auth:
          auth_url: {{ .Values.cloudConfig.auth_url }}
          username: {{ .Values.cloudConfig.username }}
          password: {{ .Values.cloudConfig.password }}
          project_domain_name: {{ .Values.cloudConfig.project_domain_name }}
          user_domain_name: {{ .Values.cloudConfig.user_domain_name }}
          project_name: {{ .Values.cloudConfig.project_name }}
        identity_api_version: {{ .Values.cloudConfig.identity_api_version }}
        verify: {{ .Values.cloudConfig.verify }}  
