apiVersion: v1
kind: Service
metadata:
  name: elastic-external
  namespace: openstack
spec:
  externalName: elasticsearch-master.lma.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}

