# 
# References
# * https://medium.com/@madushagunasekara/export-mysql-db-dump-from-kubernetes-pod-and-restore-mysql-db-on-kubernetes-pod-6f4ecc6b5a64
#
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-mariadb
  namespace: openstack
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: worker001
          containers:
            - name: backup-mariadb
              image: bigtruedata/mysqldump
              command: ["/bin/sh"]
              args: ["-c", "mysqldump -h mariadb.openstack.svc.cluster.local -u root -ppassword --all-databases > /data/tdb.sql"]
              volumeMounts:
                - name: local-storage
                  mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: local-storage
            hostPath:
              path: /data
              type: Directory
