---
- name: register public ssh-key
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Insert public key into authorized_keys file.
      blockinfile:
        path: /root/.ssh/authorized_keys
        block: "{{ lookup('file', './authorized_keys') }}"
        backup: yes

